set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'kien/ctrlp.vim'
Plugin 'tomasr/molokai'
Plugin 'preservim/nerdtree'
Plugin 'preservim/tagbar'
Plugin 'vim-airline/vim-airline'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

syntax on

nmap <leader>1 :buffer 1<CR>
nmap <leader>2 :buffer 2<CR>
nmap <leader>3 :buffer 3<CR>
nmap <leader>4 :buffer 4<CR>
nmap <leader>5 :buffer 5<CR>
nmap <leader>6 :buffer 6<CR>
nmap <leader>7 :buffer 7<CR>
nmap <leader>8 :buffer 8<CR>
nmap <leader>9 :buffer 9<CR>


" -------- nerd tree --------
map <C-n> :NERDTreeToggle<CR>
" let NERDTreeWinPos="right" " 将 NERDTree 的窗口设置在 vim 窗口的右侧（默认为左侧）


" -------- tagbar --------
nmap <F8> :TagbarToggle<CR> "让tagbar在页面左侧显示，默认右边
" let g:tagbar_left = 1

set cursorcolumn " Highlight the screen column of the cursor with CursorColumn
set cursorline " Highlight the screen line of the cursor with CursorLine
set number " 默认显示行号
set tabstop=4 " Number of spaces that a <Tab> in the file counts for
set expandtab " Use the appropriate number of spaces to insert a <Tab>
set incsearch " While typing a search command, show where the pattern, as it was typed so far, matches
set hlsearch " When there is a previous search pattern, highlight all its matches.
set showmatch " When a bracket is inserted, briefly jump to the matching one
set matchtime=5 " Tenths of a second to show the matching paren
set nowrap " 设置不自动折行
set nowrapscan " 设置不循环查找
set ambiwidth=double "设置为双字宽显示，否则无法完整显示如:☆
set colorcolumn=80
" -------- theme --------
" set background=dark
set t_Co=256
colorscheme molokai " 修改vim配色方案


" -------- air-line config --------
let g:airline#extensions#tabline#enabled = 1 " Enable enhanced tabline
let g:airline#extensions#tabline#buffer_nr_show = 1 " Enable buffer numbers show
let g:airline_powerline_fonts = 1 " Enable powerline symbols
let g:airline#parts#ffenc#skip_expected_string='utf-8[unix]' " Disable the fileformat output
let g:airline#extensions#wordcount#enabled = 0 " Disable word counting of the document/visual selection
let g:airline#extensions#whitespace#enabled = 0 " Disable detection of whitespace errors

let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''

